name: Cypress E2E Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npx http-server -p 5500 -c-1
          wait-on: 'http://127.0.0.1:5500'